name: aiml25-exam
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - pytorch
  - torchvision
  - ipykernel
  - ipython
  - ipywidgets
  - jupyter
  - markdown
  - markupsafe
  - matplotlib
  - nbclient
  - nbformat
  - pip
  - pre-commit
  - python-decouple
  - scikit-learn
  - tqdm
  - libpng
  - jpeg
  - numpy
  - networkx
  - pygraphviz
  - pip:
      - ultralytics
      - langchain-community
      - chromadb
      - ibm-watsonx-ai
      - instructor
      - langchain
      - langchain-chroma
      - langchain-core
      - langchain-ibm
      - langchain-text-splitters
      - langgraph
      - litellm
      - pandas
